---
/acquisitions/finances/config:
  get:
    x-mojo-to: Acquisitions::Finances::Finances#config
    operationId: getFinancesConfig
    description: This resource returns a list of options needed for the finances app
    summary: get the finances config
    tags:
      - finances_config
    produces:
      - application/json
    responses:
      200:
        description: The finances config
        schema:
          $ref: "../swagger.yaml#/definitions/acq_finances_config"
      400:
        description: Bad request
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      403:
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      500:
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      503:
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        acquisition: 1
