---
type: object
properties:
  borrowernumber:
    type: integer
    description: The borrowernumber of the logged in user
  permissions:
    type: object
    description: List of permissions of the logged in user used for the item lists module
additionalProperties: false
